services:
  db:
    image: postgres:17
    container_name: postgres
    restart: on-failure
    ports:
      - "5438:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: on-failure
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    networks:
      - app-network

  back:
    build:
      context: backend
      dockerfile: Dockerfile
    #container_name: back
    #ports:
    #  - "8090:8090"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - LOG_LEVEL=debug
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - SERVER_PORT=${SERVER_PORT}
      - APP_ENV=${APP_ENV}
      - GITHUB_REPOSITORY=${GITHUB_REPOSITORY}
    networks:
      - app-network
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

  front:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: front
    ports:
      - "3000:3000"
    depends_on:
      back:
        condition: service_started
    networks:
      - app-network

networks:
  app-network:
    driver: bridge