FROM golang:1.21-alpine AS builder

WORKDIR /build
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o /migrate ./cmd/app/main.go

FROM alpine:3.19
RUN apk add --no-cache ca-certificates bash
COPY --from=builder /migrate /migrate
COPY migrations/ /app/migrations/

WORKDIR /app
CMD ["/migrate", "-mode=migrate"]